# Generated by Django 4.2.9 on 2024-02-04 07:12

from django.db import migrations, models
import django.db.models.deletion
import drc.apps.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_instruction_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(height_field='height_field', null=True, upload_to=drc.apps.core.utils.recipe_image_file_path, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_image', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
